print("╔" + "═" * 30 + "╗")
print("║" + " " * 30 + "║")
print("║" + " " * 6 + "PYTHON ÇALIŞMALARI" + " " * 6 + "║")
print("║" + " " * 1 + "1- HESAP MAKİNESİ" + " " * 12 + "║")
print("║" + " " * 1 + "2- OYUNLAR" + " " * 19 + "║")
print("║" + " " * 1 + "3- ŞEKİL ÇİZDİRME" + " " * 12 + "║")
print("║" + " " * 1 + "4- TAKVİM" + " " * 20 + "║")
print("║" + " " * 1 + "5- RİTMİK SAYMA" + " " * 14 + "║")
print("║" + " " * 1 + "6- NOT HESAPLAMA" + " " * 13 + "║")
print("║" + " " * 1 + "7- ÇARPIM TABLOSU" + " " * 12 + "║")
print("║" + " " * 1 + "8- BMI HESAPLAMA" + " " * 13 + "║")
print("║" + " " * 1 + "9- DÖVİZ UYGULAMASI" + " " * 10 + "║")
print("║" + " " * 1 + "10- SICAKLIK ÇEVİRME" + " " * 9 + "║")
print("║" + " " * 1 + "11- ÇIKIŞ (e)" + " " * 16 + "║")
print("║" + " " * 9 + "SEÇİMİNİ YAP" + " " * 9 + "║")
print("╚" + "═" * 30 + "╝")